#!/bin/bash
AUDIOFORMAT='audio/x-raw-int, endianness=(int)1234, signed=(boolean)true, width=(int)16, depth=(int)16, rate=(int)48000, channels=(int)2'

    (echo 'audio sink ctr isaudio 1' ; sleep 10000000) | nc 127.0.0.1 9998 |\
      (head -1
       gst-launch -v fdsrc fd=0 ! \
        $AUDIOFORMAT            ! \
        audioconvert            ! \
        autoaudiosink
       )
