#!/bin/bash
AUDIOFORMAT='audio/x-raw-int, endianness=(int)1234, signed=(boolean)true, width=(int)16, depth=(int)16, rate=(int)48000, channels=(int)2'

gst-launch -q audiotestsrc ! $AUDIOFORMAT ! autoaudiosink
