#!/bin/bash

SRC="rtspsrc location=rtsp://admin:123456@10.0.0.52:554/mpeg4 ! decodebin name=decoder "
SHMSIZE='shm-size=54067200'
SHMOPTION="wait-for-connection=0"
SCALE="videoscale ! videoconvert"
VIDEOFORMAT='video/x-raw, format=(string)BGRA, pixel-aspect-ratio=(fraction)1/1, interlace-mode=(string)progressive, width=(int)1280, height=(int)960, framerate=(fraction)25/1'
CONTROL0=/tmp/tactical-cam-control-pipe
CONTROL1=/tmp/tactical-cam-control-pipe-live
CONTROL2=/tmp/tactical-cam-control-pipe-preview
SHMSINK0="shmsink socket-path=$CONTROL0 $SHMSIZE $SHMOPTION"
SHMSINK1="queue ! shmsink socket-path=$CONTROL1 $SHMSIZE $SHMOPTION"
SHMSINK2="queue ! shmsink socket-path=$CONTROL2 $SHMSIZE $SHMOPTION"



while true ; do
    # Remove the named pipe if it exist
    echo STARTING FEED
    rm -f $CONTROL0
    rm -f $CONTROL1
    rm -f $CONTROL2
    
    /usr/bin/gst-launch-1.0 -q $SRC ! videorate ! $SCALE ! $VIDEOFORMAT ! tee name=t1 ! $SHMSINK1 t1. ! $SHMSINK2
    # /usr/bin/gst-launch-1.0 -q $SRC ! videorate ! $SCALE ! $VIDEOFORMAT ! $SHMSINK0
    
    sleep 2
done
exit
